service: serverless-gcp-functions-circleci

provider:
    name: google
    runtime: python37
    region: us-central1
    project: ${env:PROJECT_ID}
    credentials: ~/gcloud-service-key.json

plugins:
    - serverless-google-cloudfunctions

package:
    exclude:
        - node_modules/**
        - .gitignore
        - .git/**
        - venv/**
        - .circleci/**

functions:
    test_serverless:
        handler: print_time
        events:
            - event:
                  eventType: providers/cloud.pubsub/eventTypes/topic.publish
                  resource: projects/digitaloptimisation-dev/topics/test-serverless
