service: serverless-gcp-functions-circleci

provider:
    name: google
    runtime: python37
    region: us-central1
    project: ${env:PROJECT_ID}
    credentials: ~/gcloud-service-key.json
    stage: ${opt:stage, 'dev'}
    memorySize: 256
    timeout: 28
    environment:
        PLATFORM_BASE_URL: ${env:${opt:stage, 'dev'}_PLATFORM_BASE_URL}

plugins:
    - serverless-google-cloudfunctions

package:
    exclude:
        - node_modules/**
        - .gitignore
        - .git/**
        - venv/**
        - .circleci/**

functions:
    test_serverless:
        handler: print_time
        events:
            - event:
                  eventType: providers/cloud.pubsub/eventTypes/topic.publish
                  resource: projects/${env:PROJECT_ID}/topics/test-serverless
