version: 2.1
executors:
    my-executor:
        docker:
            - image: circleci/python:3.7.2

commands:
    set-up:
        description:  "Set up env for serverless"
        steps:
            - checkout
            - run:
                command: |
                    curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
                    sudo apt-get install -y nodejs npm
                    npm install
    deploy:
        description: "Deploy functions to GCP"
        parameters:
            service-key:
                type: string
                default: "DEVELOPMENT_SERVICE_KEY"
            project-id:
                type: string
                default: "digitaloptimisation-dev"
            stage:
                type: string
                default: "dev"
        steps:
            - run:
                command: |
                    export PROJECT_ID=<<parameters.project-id>>
                    echo $<<parameters.service-key>> > ${HOME}/gcloud-service-key.json
                    ./node_modules/.bin/sls deploy --stage <<parameters.stage>>

jobs:
    security-checks:
        docker:
            - image: docker:stable
        steps:
            - checkout
            - setup_remote_docker
            - run: sh ci/security_checks.sh
            - store_artifacts:
                path: /tmp/artifacts/hawkeye_report.json

    build:
        executor: my-executor
        steps:
            - checkout
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    sh ci/static-code-check.sh
                    sh ci/unit-test.sh
            - store_artifacts:
                path: test-results

    deploy-dev:
        executor: my-executor
        steps:
            - set-up
            - deploy

    deploy-staging:
        executor: my-executor
        steps:
            - set-up
            - deploy:
                service-key: STAGING_SERVICE_KEY
                project-id: digitaloptimisation-staging
                stage: staging

    deploy-prod:
        executor: my-executor
        steps:
            - set-up
            - deploy:
                service-key: PROD_SERVICE_KEY
                project-id: digitaloptimisation-prod
                stage: prod

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy-dev:
                  requires:
                      - build

nightly:
    triggers:
        - schedule:
            cron: "0 1 * * *"
            filters:
                branches:
                    only:
                        - master
    jobs:
        - security-checks
